---
title: "R Notebook"
output: html_notebook
---
# Class Exercise 1

## 1. Introduction
Satisfaction of the public with democracy is crucial for the functioning of
political ecosystems. We therefore investigate predictors for individuals'
satisfaction in Switzerland by having a look at the political interest and
media usage of the Swiss respondents from the European Social Survey. A 
regression analysis will then be conducted to assess the influence of some 
variables on satisfaction with democracy. Consequently, the research question
addressed here is:
- Does TV usage and political interest affect citizens' satisfaction with 
democracy?
With regards to the above question, following hypotheses have been elaborated 
which later will be tested using empirical data. 

1. Increased consumption of political contents on TV results in a lower 
satisfaction with democracy.
2. Higher political interest results in a lower satisfaction with democracy.

The confirmation of these hypotheses would show that low satisfaction with 
democracy can be a result of a high political literacy, rather than individuals
being not satisfied because they are not well informed about political affairs. 

## 2. Methods
Multiple regression analysis will be used as the dependent variable *stfdem* 
(satisfaction with democracy) is continuous. The variables of interest *tvpol*
(amount of political TV consumption) and *polintr* (political interest) are 
regarded as categorical data, thus for the analysis a reference category is built
in order to assess effects. By integrating also the variables *trstprl* (trust
in parliament), *gndr* (gender) and *agea* (age) into the model, we can control
for their effects. 

## 3. Results
```{r, echo=TRUE}
library(stargazer)
dat <- readRDS(here("data", "data_processed.rds")) #load data

# modelling satisfaction with democracy
model_stfdem <- lm(stfdem ~ factor(tvpol) + factor(polintr) + trstprl + factor(gndr) 
            + agea, dat)
summary(model_stfdem)

stargazer(model, style = "ajps", out = here("data", "table.html"))
```





## 4. Discussion